cp -fv ./update/ggml/src/ggml-alloc.c ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/ggml/src/ggml-backend-impl.h ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/ggml/src/ggml-backend.c ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/ggml/src/ggml-impl.h ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/ggml/src/ggml-metal.m ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/ggml/src/ggml-metal.metal ../Sources/llmfarm_core_cpp/
cp -fv ./update/ggml/src/ggml-quants.c ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/ggml/src/ggml-quants.h ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/ggml/src/ggml-blas.cpp ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/ggml/src/ggml.c ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/ggml/src/ggml-common.h ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/ggml/src/ggml-aarch64.c ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/ggml/src/ggml-aarch64.h ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/ggml/include/ggml-metal.h ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/ggml/include/ggml.h ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/ggml/include/ggml-backend.h ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/ggml/include/ggml-alloc.h ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/ggml/include/ggml-blas.h ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/src/llama.cpp ../Sources/llmfarm_core_cpp/llama/
cp -fv ./update/src/unicode-data.cpp ../Sources/llmfarm_core_cpp/llama/
cp -fv ./update/src/unicode-data.h ../Sources/llmfarm_core_cpp/llama/
cp -fv ./update/src/unicode.cpp ../Sources/llmfarm_core_cpp/llama/
cp -fv ./update/src/unicode.h ../Sources/llmfarm_core_cpp/llama/
cp -fv ./update/include/llama.h ../Sources/llmfarm_core_cpp/spm-headers/
cp -fv ./update/ggml/src/llamafile/sgemm.h ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/ggml/src/llamafile/sgemm.cpp ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/common/grammar-parser.cpp ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/common/grammar-parser.h ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/common/train.cpp ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/common/train.h ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/common/common.cpp ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/common/common.h ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/common/json.hpp ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/common/json-schema-to-grammar.h ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/common/json-schema-to-grammar.cpp ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/common/sampling.h ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/common/log.h ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/common/console.h ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/common/console.cpp ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/common/sampling.cpp ../Sources/llmfarm_core_cpp/ggml/
cp -fv ./update/examples/export-lora/export-lora.cpp ../Sources/llmfarm_core_cpp/finetune/
cp -fv ./update/examples/finetune/finetune.cpp ../Sources/llmfarm_core_cpp/finetune/
cp -fv ./update/examples/llava/llava.cpp ../Sources/llmfarm_core_cpp/llava/
cp -fv ./update/examples/llava/llava.h ../Sources/llmfarm_core_cpp/spm-headers/
cp -fv ./update/examples/llava/llava-cli.cpp ../Sources/llmfarm_core_cpp/llava/
cp -fv ./update/examples/llava/clip.cpp ../Sources/llmfarm_core_cpp/llava/
cp -fv ./update/examples/llava/clip.h ../Sources/llmfarm_core_cpp/spm-headers/
